#!/usr/bin/env bash

prefix="vcw_module_vcwc_grafana_traefik__$1"
prefix="vcw_module_vcwc_grafana_traefik__$1"

if [[ "vcw_module_vcwc_grafana_traefik__grafana_grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_vcwc_grafana_traefik__grafana_grafana_volume
fi

if [[ "vcw_module_vcwc_grafana_traefik__grafana_grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcw_module_vcwc_grafana_traefik__grafana_grafana_volume:/var/lib/grafana ${VCW_REGISTRY}hkvb/controlplane.vcw console untar /source/hkvb/grafana/traefik/_module/volumes/grafana_grafana_volume.tar
fi
