#!/usr/bin/env bash

prefix="vcw_module_hkvb_grafana__$1"
prefix="vcw_module_hkvb_grafana__$1"

if [[ "vcw_module_hkvb_grafana__grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_grafana__grafana_volume
fi
